# Generated by Django 5.1.7 on 2025-03-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=1000)),
                ('author', models.CharField(max_length=30)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
