# Generated by Django 5.1.7 on 2025-04-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_content_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content1',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
