# Generated by Django 5.1.7 on 2025-04-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_blogcomment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='auther',
            field=models.CharField(max_length=500),
        ),
    ]
