# Generated by Django 5.1.5 on 2025-04-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_remove_blogcomment_likes_alter_post_auther'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content2',
        ),
    ]
